### ISSUE TITLE
Sounds GREAT but it won't open at all..

### ISSUE THREAD

**Issue by VaLeTecK** [Lee-matod/GProfiles#1]
So.. i basically download the last version and run but nothing happen.. what i do wrong?? Something else to be well explained on how this work?? 
Ty :D

**Comment by Lee-matod** [comment]
Hi, thank you for taking the time to report this.

There are a couple of things that may cause this off the top of my head. Mainly that GProfiles cannot locate your Logitech settings. Please keep in mind that for this application to work, you should also have [Logitech G HUB](https://www.logitechg.com/en-us/innovation/g-hub.html) installed in your system.
If you do have it installed, check that `%LOCALAPPDATA%\LGHUB` is an existing directory, and that there is a `settings.db` file in that folder.

I'm currently working on improving error handling, which should help further debug the issue in case the above did not solve it.

Cheers!

**Comment by VaLeTecK** [comment]
Hello and ty for the answer

Of course i have G HUB installed and the settings.db file in the appdata/LGHUB path.
My doubt was if it won't open because there's anything else to do, like if it's important to execute while LGHub is running or not, or it just work on edit properly the settings.db file and nothing else needed.

Btw no error or something like that.. just nothing open in the process manager when executing.

Cheers

**Comment by Lee-matod** [comment]
Hello,

GProfiles doesn't need LGHUB to be running in the background for it to work properly. It only interacts with the `settings.db` file. 
Furthermore, no other prerequisites should be required for the application to run correctly. It should be able to start as long as you have a valid `settings.db` in the default directory.

I just pushed out a new micro release which adds proper error handling for some cases, so let me know if anything shows up so I can further take a look into it.

Thanks!

**Comment by VaLeTecK** [comment]
Hello again
First of all thanks for support!!

So, i've just tried the new release and now i get the error %LOCALAPPDATA%\LGHUB is not a directory, but, ofc the directory is there and working like always.. what it could be at this point? 

![image](https://github.com/user-attachments/assets/6a2740eb-4f9b-48ed-895c-bb3e2425327b)

**Comment by Lee-matod** [comment]
Hey,

Thanks for checking it out in such short notice. It looks like your `LOCALAPPDATA` environment variable might not be set correctly. Please verify that it is pointing to the correct location. You can check your environment variables by running the following command in a Windows Powershell instance:
```ps
Get-ChildItem -Path Env:
```
This will display all of your env vars formatted into a "Name" and "Value" columns. Simply find the row that says "LOCALAPPDATA" and ensure that it points to the same directory where your `LGHUB` folder is located.

**Comment by VaLeTecK** [comment]
Well, just checked and it's all right to where we need :/
![image](https://github.com/user-attachments/assets/7870e597-f838-459a-9769-9af191bffaec)

**Comment by Lee-matod** [comment]
Hey,

After some more debugging, I think I figured out what wasn't working correctly. I made a hotfix to release it. Please let me know if the issue was resolved.

Thank you very much in advance for your patience and cooperation.

**Comment by VaLeTecK** [comment]
Just tried and seems that APPDATA works now but i'm getting this double error insteat right after opening 
![image](https://github.com/user-attachments/assets/f4223697-e336-4420-8b5c-8cffaa82236c)

**Comment by Lee-matod** [comment]
Thanks. I updated the release with yet another hotfix. Sorry for the inconvenience.

**Comment by Lee-matod** [comment]
Let me know if you come across any other problems, or if it's fine to close this issue.

**Comment by VaLeTecK** [comment]
So.. i'm trying it right now.. and IT WORK!! Good job mate!

I like a lot the interface but unfortunatelly there's still an issue..
There's no way to swipe between game profiles..
I'm trying with mouse scroll, by dragging, with kb arrows.. nothing seems to work
Any clue or just something is missing?

**Comment by Lee-matod** [comment]
Thank you! I appreciate it.

You should be able to scroll through the carousel by either holding down shift and scrolling, or by dragging the little scrollbar which should be above the gray area, where you can edit the game profile properties.
Unfortunately, as far as I'm aware, horizontally scrolling using just the scroll wheel isn't natively available through the UI framework I'm using. Maybe I can come up with some hacky fix for better user experience in the future.

Cheers!

**Comment by VaLeTecK** [comment]
OOOOO niceeee.. the little gray scrollbar is barely visible.. i suggest to add somewhere a tip that tell you about the shift+scroll things..
So far, the only other issue i've found is regarding the windows resize that don't work when you expand.. the app area will remain the same size as it open..

I'll give you some more feedback in the next days after using it and doing some stuffs :D

Anyway really appreciate your work.. i (and a lot more people) really hate how Logi have ruined  and replaced their good old Logitech Gaming Software with this somehow trash GHUB..
Keep it up the good work!!

Cheers!

**Comment by Lee-matod** [comment]
The window size being static is intentional. It mostly helps with preventing everything from breaking when resizing, and it also allows me to create a design which I know will look the same regardless of where the application is being used.

I would very much appreciate the feedback, thank you!

I'll close this issue for now then. Feel free to reopen it or create a new one.

Have a lovely rest of the day!
